name: Trigger workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      fail:
        description: 'Force failure'
        required: false
        type: boolean

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Pass condition
        if: ${{ !inputs.fail }}
        run: echo 'passed'
      - name: Fail condition
        if: ${{ inputs.fail }}
        run: exit 1

